# Generated by Django 5.0.1 on 2024-01-11 06:39

import Services_Model.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='نام')),
                ('title_en', models.CharField(max_length=255, verbose_name='نام در url')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='اسم')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='اسم انگلیسی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('bed', models.IntegerField(blank=True, null=True, verbose_name='تعداد تخت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=Services_Model.models.upload_image_path, verbose_name='تصویر')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='امکانات')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='اسم')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Hotel_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Services_Model.models.upload_image_path, verbose_name='تصویر گالری')),
                ('hotel_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.hotel', verbose_name='هتل')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='option',
            field=models.ManyToManyField(to='Services_Model.option', verbose_name='امکانات'),
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='اسم')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('image', models.ImageField(upload_to=Services_Model.models.upload_image_path, verbose_name='تصویر')),
                ('option', models.ManyToManyField(to='Services_Model.option', verbose_name='امکانات')),
                ('type_res', models.ManyToManyField(to='Services_Model.restaurants_type', verbose_name='نوع رستوران')),
            ],
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='اسم')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=Services_Model.models.upload_image_path, verbose_name='تصویر')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.city', verbose_name='شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Public_Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='اسم')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Services_Model.models.upload_image_path, verbose_name='تصویر')),
                ('tourist_places', models.ManyToManyField(to='Services_Model.tourism', verbose_name='مکان توریستی')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='tourist_places',
            field=models.ManyToManyField(to='Services_Model.tourism', verbose_name='مکان توریستی'),
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='اسم')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=Services_Model.models.upload_image_path, verbose_name='تصویر')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.city', verbose_name='شهر')),
                ('option', models.ManyToManyField(to='Services_Model.option', verbose_name='امکانات')),
                ('tourist_places', models.ManyToManyField(to='Services_Model.tourism', verbose_name='مکان توریستی')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Villa_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Services_Model.models.upload_image_path, verbose_name='تصویر گالری')),
                ('villa_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.villa', verbose_name='ویلا')),
            ],
        ),
    ]
