# Generated by Django 5.0.1 on 2024-01-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_hotel_picture',
            old_name='image',
            new_name='image_hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='gallery',
            field=models.ManyToManyField(to='Services_Model.gallery_hotel_picture', verbose_name='تصاویر بیشتر'),
        ),
        migrations.AlterField(
            model_name='gallery_hotel_picture',
            name='hotel_type',
            field=models.CharField(max_length=255, verbose_name='نوع اتاق'),
        ),
    ]
