# Generated by Django 5.0.1 on 2024-01-11 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Model', '0002_rename_image_gallery_hotel_picture_image_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='رزرو شده/نشده'),
        ),
        migrations.CreateModel(
            name='Count_Room_Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_room', models.IntegerField(verbose_name='تعداد اتاق')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.hotel', verbose_name='هتل')),
            ],
        ),
    ]
