# Generated by Django 5.0.1 on 2024-01-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Model', '0004_restaurants_tourist_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='tourist_places',
            field=models.ManyToManyField(blank=True, to='Services_Model.tourism', verbose_name='مکان توریستی'),
        ),
    ]
