# Generated by Django 5.0.1 on 2024-01-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Model', '0005_alter_restaurants_tourist_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='اجاره'),
        ),
    ]
