# Generated by Django 5.0.1 on 2024-01-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Model', '0006_villa_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='رزرو شده/نشده'),
        ),
    ]
