# Generated by Django 5.0.1 on 2024-01-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Model', '0007_villa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.IntegerField(blank=True, null=True, verbose_name='اتاق'),
        ),
    ]
