# Generated by Django 5.0.1 on 2024-01-11 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services_Model', '0003_hotel_status_count_room_hotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_hotel', models.CharField(max_length=250, verbose_name='تاریخ رزرو')),
                ('out_hotel', models.CharField(max_length=250, verbose_name='مدت زمان ماندن')),
                ('price', models.BigIntegerField(verbose_name='هزینه')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.hotel', verbose_name='هتل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
