# Generated by Django 5.0.1 on 2024-01-11 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Model', '0001_initial'),
        ('Services_Model', '0007_villa_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_hotel', models.CharField(max_length=250, verbose_name='تاریخ رزرو')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='تعداد شب ماندگاری')),
                ('price', models.BigIntegerField(verbose_name='هزینه')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.hotel', verbose_name='هتل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_hotel', models.CharField(max_length=250, verbose_name='تاریخ رزرو')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='تعداد شب ماندگاری')),
                ('price', models.BigIntegerField(verbose_name='هزینه')),
                ('Villa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.hotel', verbose_name='ویلا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
