# Generated by Django 5.0.1 on 2024-01-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Model', '0002_reservation_hotel_reservation_villa_and_more'),
        ('Services_Model', '0007_villa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_villa',
            name='Villa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Model.villa', verbose_name='ویلا'),
        ),
    ]
